name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # Se activa al hacer push a "main"

jobs:
  build-and-push:
    runs-on: windows-latest  # Ejecuta en un runner de Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: trsbraulio
          password: Br@ulio0898!

      - name: Build and push Docker image
        run: |
          docker build -t trsbraulio/plan-padrino-react:latest .
          docker push trsbraulio/plan-padrino-react:latest

  deploy:
    needs: build-and-push  # Depende del job anterior
    runs-on: ubuntu-latest  # Usa un runner de Linux para SSH

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull trsbraulio/plan-padrino-react:latest
            docker stop plan-padrino || true
            docker rm plan-padrino || true
            docker run -d -p 3000:3000 --name plan-padrino trsbraulio/plan-padrino-react:latest
